apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web
    spec:
      containers:
      - image: docker.io/cooktheryan/web:395cd1b0784b95745c2bb144c7bc2af8cef50993
        name: web
        ports:
        - containerPort: 8443
        resources: {}
status: {}
