apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web
    spec:
      containers:
      - image: docker.io/cooktheryan/web:62e86f37f86ac6de5958db3b6908f4de8e74dc7b
        name: web
        ports:
        - containerPort: 8443
        resources: {}
status: {}
